### ISSUE TITLE
Why is chakra ui's "select" component direction upwards in machine selector

### ISSUE THREAD

**Issue by aquibbaig** [bench-routes/dashboard#14]
<img width="361" alt="Image" src="https://user-images.githubusercontent.com/26324376/123753581-a56ec380-d8d7-11eb-9722-e66d43852e5a.png">

I haven't researched more on it, but it can be a good first issue. The solution can be replacing it with a "Menu" component instead

**Comment by ruddi10** [comment]
Hey @aquibbaig dont know why this is happening on your local environment its totally fine on mine

**Comment by satyaarthchhabra** [comment]
hey, I would love to work on this issue . but i am getting  an error , it would be great if you could help me through it @aquibbaig  @ruddi10  . the issue is  i am gettting this network error . i have also started the backend but still i am getting this error 
![Capture](https://user-images.githubusercontent.com/56510402/133213898-42fbbb90-3651-49c5-aff6-811c7c4c628d.PNG)

**Comment by ruddi10** [comment]
I think your backend stopped running due to some error can you share the ss of your terminal for both backend and frontend

**Comment by satyaarthchhabra** [comment]
hey , yes i just noted here is an issue with backend here are its logs 
echo "compiling go-code and executing bench-routes"
compiling go-code and executing bench-routes
echo "using 9990 as default service listener port"
using 9990 as default service listener port
go run src/*.go 9990
level=info ts=2021-09-14T10:40:02.836Z caller=main.go:45 msg=configuration out="[{sample-google 5s https www.google.com /search get map[Content-Type:json] map[q:bench-routes] map[]}]"
level=info ts=2021-09-14T10:40:02.836Z caller=main.go:53 msg="launching machine routine"
level=info ts=2021-09-14T10:40:02.843Z caller=main.go:67 msg="launching monitor routine"
level=debug ts=2021-09-14T10:40:02.851Z caller=api.go:53 msg="Updated API domain map"
level=info ts=2021-09-14T10:40:02.852Z caller=main.go:117 msg="Listening at :9990"
level=error ts=2021-09-14T10:40:08.852Z caller=main.go:161 msg="running monitor" error="running monitor: job: sample-google: error in sending request: Get \"https://www.google.com/search?q=bench-routes\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
exit status 1
make: *** [Makefile:19: run] Error 1

**Comment by ruddi10** [comment]
You are having a storage folder right? Delete all its content and try restarting the backend

**Comment by aquibbaig** [comment]
@satyaarthchhabra thanks for showing your interest in improving bench-routes dashboard, I think @ruddi10 has pointed out steps to fix the errors. After that, can you please let me know if you can reproduce this issue?

**Comment by satyaarthchhabra** [comment]
hey i have got all issues resolved but still the dashboard looks like the same 
bench-routes(backend ):
echo "compiling go-code and executing bench-routes"
compiling go-code and executing bench-routes
echo "using 9990 as default service listener port"
using 9990 as default service listener port
go run src/*.go 9990
level=info ts=2021-09-15T08:18:28.093Z caller=main.go:45 msg=configuration out="[{sample-google 5s https www.google.com /search get map[Content-Type:json] map[q:bench-routes] map[]}]"
level=info ts=2021-09-15T08:18:28.093Z caller=main.go:53 msg="launching machine routine"
level=info ts=2021-09-15T08:18:28.094Z caller=chain.go:59 creatingin-memorychain'%s'withpathat'%s'=www.google.com_ping storage/www.google.com_ping.json=(MISSING)
level=info ts=2021-09-15T08:18:28.106Z caller=chain.go:59 creatingin-memorychain'%s'withpathat'%s'=www.google.com_jitter storage/www.google.com_jitter.json=(MISSING)
level=info ts=2021-09-15T08:18:28.115Z caller=main.go:67 msg="launching monitor routine"
level=info ts=2021-09-15T08:18:28.118Z caller=chain.go:59 creatingin-memorychain'%s'withpathat'%s'=sample-google_monitor storage/sample-google_monitor.json=(MISSING)
level=debug ts=2021-09-15T08:18:28.130Z caller=api.go:53 msg="Updated API domain map"
level=info ts=2021-09-15T08:18:28.130Z caller=main.go:117 msg="Listening at :9990"
level=warn ts=2021-09-15T08:19:03.017Z caller=api.go:93 component=api msg="ping: path not found at ./storage/_ping.json"
level=warn ts=2021-09-15T08:19:03.024Z caller=api.go:102 component=api msg="jitter: path not found at ./storage/_jitter.json"
2021/09/15 13:49:03 http: panic serving [::1]:56880: interface conversion: interface {} is nil, not 
evaluate.Response
goroutine 57 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1801 +0xb9
panic({0x6e67c0, 0xc000226bd0})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/bench-routes/bench-routes/src/lib/api.(*API).getDomainEntity(0xc00009ba70, {0x7a5df0, 0xc0002141c0}, 0xc0001fe000)
        /mnt/d/react learn/bench-routes/src/lib/api/api.go:123 +0xadb
net/http.HandlerFunc.ServeHTTP(0xc0003e4600, {0x7a5df0, 0xc0002141c0}, 0xc000180000)
        /usr/local/go/src/net/http/server.go:2046 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001aa540, {0x7a5df0, 0xc0002141c0}, 0xc00019c500)    
        /home/satyaarth/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/rs/cors.(*Cors).Handler.func1({0x7a5df0, 0xc0002141c0}, 0xc00019c500)
        /home/satyaarth/go/pkg/mod/github.com/rs/cors@v1.8.0/cors.go:219 +0x1bd
net/http.HandlerFunc.ServeHTTP(0xc0003e6020, {0x7a5df0, 0xc0002141c0}, 0x461c8e)
        /usr/local/go/src/net/http/server.go:2046 +0x2f
net/http.serverHandler.ServeHTTP({0xc0002265a0}, {0x7a5df0, 0xc0002141c0}, 0xc00019c500)
        /usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc0001fe280, {0x7a7300, 0xc0000e4090})
        /usr/local/go/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3033 +0x4e8
2021/09/15 13:49:03 http: panic serving [::1]:56882: interface conversion: interface {} is nil, not 
evaluate.Response
goroutine 25 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1801 +0xb9
panic({0x6e67c0, 0xc000226090})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/bench-routes/bench-routes/src/lib/api.(*API).getDomainEntity(0xc00009ba70, {0x7a5df0, 0xc000350460}, 0xc0001fe000)
        /mnt/d/react learn/bench-routes/src/lib/api/api.go:123 +0xadb
net/http.HandlerFunc.ServeHTTP(0xc00019c600, {0x7a5df0, 0xc000350460}, 0xc000180000)
        /usr/local/go/src/net/http/server.go:2046 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001aa540, {0x7a5df0, 0xc000350460}, 0xc0003e4500)    
        /home/satyaarth/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/rs/cors.(*Cors).Handler.func1({0x7a5df0, 0xc000350460}, 0xc0003e4500)
        /home/satyaarth/go/pkg/mod/github.com/rs/cors@v1.8.0/cors.go:219 +0x1bd
net/http.HandlerFunc.ServeHTTP(0xc0000bc070, {0x7a5df0, 0xc000350460}, 0x461c8e)
        /usr/local/go/src/net/http/server.go:2046 +0x2f
net/http.serverHandler.ServeHTTP({0xc00014a480}, {0x7a5df0, 0xc000350460}, 0xc0003e4500)
        /usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc0000b6a00, {0x7a7300, 0xc0000e4090})
        /usr/local/go/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3033 +0x4e8
2021/09/15 13:49:03 http: panic serving [::1]:56878: interface conversion: interface {} is nil, not 
evaluate.Response
goroutine 56 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1801 +0xb9
panic({0x6e67c0, 0xc00014a1e0})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/bench-routes/bench-routes/src/lib/api.(*API).getDomainEntity(0xc00009ba70, {0x7a5df0, 0xc00005c0e0}, 0xc0001fe000)
        /mnt/d/react learn/bench-routes/src/lib/api/api.go:123 +0xadb
net/http.HandlerFunc.ServeHTTP(0xc0003e4000, {0x7a5df0, 0xc00005c0e0}, 0x9a1aa0)
        /usr/local/go/src/net/http/server.go:2046 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001aa540, {0x7a5df0, 0xc00005c0e0}, 0xc0003e4400)    
        /home/satyaarth/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/rs/cors.(*Cors).Handler.func1({0x7a5df0, 0xc00005c0e0}, 0xc0003e4400)
        /home/satyaarth/go/pkg/mod/github.com/rs/cors@v1.8.0/cors.go:219 +0x1bd
net/http.HandlerFunc.ServeHTTP(0xc0003e6020, {0x7a5df0, 0xc00005c0e0}, 0x461c8e)
        /usr/local/go/src/net/http/server.go:2046 +0x2f
net/http.serverHandler.ServeHTTP({0xc0002264b0}, {0x7a5df0, 0xc00005c0e0}, 0xc0003e4400)
        /usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc0001fe0a0, {0x7a7300, 0xc0000e4090})
        /usr/local/go/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3033 +0x4e8
2021/09/15 13:49:03 http: panic serving [::1]:56884: interface conversion: interface {} is nil, not 
evaluate.Response
goroutine 27 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1801 +0xb9
panic({0x6e67c0, 0xc000564330})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/bench-routes/bench-routes/src/lib/api.(*API).getDomainEntity(0xc00009ba70, {0x7a5df0, 0xc000350000}, 0xc0001fe000)
        /mnt/d/react learn/bench-routes/src/lib/api/api.go:123 +0xadb
net/http.HandlerFunc.ServeHTTP(0xc0001f2300, {0x7a5df0, 0xc000350000}, 0xc000080000)
        /usr/local/go/src/net/http/server.go:2046 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001aa540, {0x7a5df0, 0xc000350000}, 0xc0001f2000)    
        /home/satyaarth/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/rs/cors.(*Cors).Handler.func1({0x7a5df0, 0xc000350000}, 0xc0001f2000)
        /home/satyaarth/go/pkg/mod/github.com/rs/cors@v1.8.0/cors.go:219 +0x1bd
net/http.HandlerFunc.ServeHTTP(0xc0000bc0c0, {0x7a5df0, 0xc000350000}, 0x461c8e)
        /usr/local/go/src/net/http/server.go:2046 +0x2f
net/http.serverHandler.ServeHTTP({0xc0005640c0}, {0x7a5df0, 0xc000350000}, 0xc0001f2000)
        /usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc0001fe280, {0x7a7300, 0xc0000e4090})
        /usr/local/go/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3033 +0x4e8

frontend (bench-routes):

Compiled successfully!

You can now view bench-routes-dashboard in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://192.168.37.244:3000

Note that the development build is not optimized.
To create a production build, use yarn build.

**Comment by aquibbaig** [comment]
@satyaarthchhabra Are you on Linux?

**Comment by aquibbaig** [comment]
@satyaarthchhabra Thanks for bringing this up. I believe there are at least some ambiguities/errors in the way we fetch data from bench-routes-backend. Please go ahead and open an issue saying "Not able to bootstrap bench-routes-dashboard" listing screenshots for the issue and once you start the dashboard, make sure you drop a screenshot of the "Networks" tab. I will assign myself to it and we can fix them, thanks!

**Comment by ruddi10** [comment]
@aquibbaig hey actually earlier I faced similar issue the reason was the shutting of backend on its own and tushar told me that the reason behind this is frequent on off cause duplication leading to problems so the only solution was to delete all the files in storage folder

**Comment by satyaarthchhabra** [comment]
Hi @ruddi10  , what happens is when i delete the storage folder ,  " error running ping : socket: permission denied" error comes and i am not able to get how things are going . here are its log 

level=info ts=2021-09-17T19:58:19.277Z caller=main.go:45 msg=configuration out="[{sample-google 5s https www.google.com /search get map[Content-Type:json] map[q:bench-routes] map[]}]"
level=info ts=2021-09-17T19:58:19.277Z caller=main.go:53 msg="launching machine routine"
level=info ts=2021-09-17T19:58:19.284Z caller=main.go:67 msg="launching monitor routine"
level=debug ts=2021-09-17T19:58:19.300Z caller=api.go:53 msg="Updated API domain map"
level=info ts=2021-09-17T19:58:19.300Z caller=main.go:117 msg="Listening at :9990"
level=error ts=2021-09-17T19:58:25.302Z caller=main.go:161 msg="running monitor" error="running monitor: job: sample-google: error in sending request: Get \"https://www.google.com/search?q=bench-routes\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
exit status 1
make: *** [Makefile:19: run] Error 1

**Comment by aquibbaig** [comment]
I think this is not a good place to track this discussion, we should do that in a new issue that matches the context

**Comment by satyaarthchhabra** [comment]
Hi @aquibbaig  and @ruddi10 ,  i  have created a new issue at https://github.com/bench-routes/bench-routes/issues/506

**Comment by ruddi10** [comment]
Hey @satyaarthchhabra are you using windows?

**Comment by satyaarthchhabra** [comment]
@ruddi10   yes windows 10

**Comment by saideepesh000** [comment]
hey @ruddi10 @aquibbaig , shall I work on this issue

**Comment by ruddi10** [comment]
Sure go ahead first of all please confirm is this problem reproducible on your system. As I wasn't able to reproduce it

**Comment by ruddi10** [comment]
> hey @ruddi10 @aquibbaig , shall I work on this issue

Sure go ahead first of all please confirm is this problem reproducible on your system. As I wasn't able to reproduce it

**Comment by ruddi10** [comment]
@aquibbaig This bug is not reproducible on my system can we close this issue or do we need to keep this?

**Comment by aquibbaig** [comment]
I have a better idea, lets replace this component with a MenuList.
